language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'grunt-openfin' ]; then cd .. && eval "mv $currentfolder grunt-openfin" && cd grunt-openfin; fi
